### ISSUE TITLE
Associar as issues com os respectivos labels dos responsáveis

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/sysgraph#10]
@viniciussoaresti Criei labels com o login dos participantes do projeto para que você associe cada issue ao seu respectivo responsável. Veja que **todas** as issues devem estar associadas.

**Comment by MatheusDias18** [comment]
Labels atualizados!

**Comment by vinisoaresti** [comment]
Ainda não finalizado.

**Comment by MatheusDias18** [comment]
labels atualizados.

**Comment by fabriciofx** [comment]
@viniciussoaresti Se eu não me engano a questão dos labels é pq havia uma questão de permissão no GitHub que apenas permitia ao Admin do repositório fazer assign de uma issue a alguém. Os labels, por outro lado, qualquer um podia fazer. Mas parece que isso mudou. Vou investigar depois te trago um feedback, ok?

**Comment by MatheusDias18** [comment]
@fabriciofx o senhor já conseguiu investigar pra poder nos dar feedback e fecharmos a issue?

**Comment by fabriciofx** [comment]
@MatheusDias18 @viniciussoaresti @BarrosPedro Segue o feedback acerca sob a utilização dos logins do GitHub como labels das issues:

1. Apenas colaboradores de um projeto/repositório podem atribuir (assign) uma issue para outros colaboradores ou colocar labels em uma issue;
2. Eu, sendo colaborador, só posso atribuir uma issue a uma pessoa que também é colaborador do mesmo projeto/repositório. E se eu precisar atribuir aquela issue a uma pessoa que não é colaborador? Eu posso criar um label para ela (com o login dela no GH) e etiquetar a issue, dessa forma ficando claro que aquela issue foi associada a determinado usuário que não necessariamente é colaborador do projeto;
3. Só é possível fazer buscas nas issues por um author por vez. Em compensação, posso fazer buscas por mais de um label por vez. Assim, utilizando o esquema de login nos labels, posso fazer uma busca por issues que foram atribuídas a mais de uma pessoa (mas IMHO isso é um erro de gerenciamento: cada issue só deveria ter **UM** responsável);
4. Visualmente fica melhor de ver e entender quais issues estão associadas a quais pessoas utilizando o esquema de labels nos logins.

Por estas razões (e principalmente a número **2**) é que eu utilizo o esquema de criar labels com os logins dos usuários do GH. Se as razões não ficaram claras ou se vocês não concordarem, favor comentar aqui nessa issue.

**Comment by vinisoaresti** [comment]
@fabriciofx Segundo @BarrosPedro , a abertura de issues e colocação de labels pra ele não é permitida. Isso seria alguma desinformação ou configuração errada minha?
