### ISSUE TITLE
Dividir as issues em issues menores

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/sysgraph#12]
@viniciussoaresti Você notou que a maioria das issues tem mais de um responsável? Isso é sinal de que elas têm muitas funcionalidades. Quebre-as em issues menores e atribua *uma* pessoa para cada issue. Em caso de dúvidas, olhe como foi feito no [saudegaranhuns](https://github.com/ifpe-cti/saudegaranhuns/issues).

**Comment by vinisoaresti** [comment]
@fabriciofx sim senhor. O sr. poderia responder a pergunta feita na issue #10?

**Comment by MatheusDias18** [comment]
As que se mostraram necessárias foram divididas.
