### ISSUE TITLE
Diagramas de Classe

### ISSUE THREAD

**Issue by MatheusDias18** [ifpe-cti/sysgraph#13]
Diagramas de Classe, será feito após o planejamento e o cronograma do projeto #8.

**Comment by fabriciofx** [comment]
@MatheusDias18 Dê preferencia por usar o [PlantUML](http://plantuml.com/). Dê uma olhada no [aqui](https://github.com/ifpe-cti/saudegaranhuns/blob/master/pom.xml) para ver como você pode aplicá-lo a seu projeto.

**Comment by MatheusDias18** [comment]
Diagramas de classe "prévio" concluído, sujeito a mudanças.
