### ISSUE TITLE
Pasta "termos" com documentos desnecessários

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/sysgraph#14]
@viniciussoaresti A pasta `termos` que está nesse repositório é desnecessário. São documentos refentes apenas a oficialização do PPO dos estudantes. Não tem relação com o projeto. Você está prestando atenção no que entra no seu repositório? Se eu quiser colocar um código pra roubar senhas, você nem ficará sabendo? Viu como é importante a revisão do código?
@vsnepomuceno Viu como é importante a revisão do código pelo arquiteto?

**Comment by vinisoaresti** [comment]
@fabriciofx Eu vi sim esses documentos. Eu importei pra podermos imprimir e entregar depois à pessoa responsável por recebê-los, depois disso, deletando os arquivos.

**Comment by fabriciofx** [comment]
@viniciussoaresti Estes documentos ainda não estão prontos. Ainda estão sendo editados e analisados. Não se preocupe, que no devido tempo, serão apresentados a você, ok? 😄
