### ISSUE TITLE
Cronograma de Atividades 

### ISSUE THREAD

**Issue by BarrosPedro** [ifpe-cti/sysgraph#15]
Cronograma (contar quantas semanas há até agosto, ser realista e tomar cuidado com os feriados) e divisão de quem realizará as atividades.

**Comment by BarrosPedro** [comment]
@viniciussoaresti Coloca os labels de @MatheusDias18 e o meu. Por Favor.

**Comment by vinisoaresti** [comment]
Segue exemplo.
![image](https://user-images.githubusercontent.com/36902457/38222934-4a447004-36be-11e8-8124-b6dc479b24e9.png)

**Comment by BarrosPedro** [comment]
# CRONOGRAMA SEMANAL
<table>
<tr>
  <td colspan="3"></td>
  <td colspan="3"></td>
 <td colspan="4" ><center><b>Abril</b></center></td>
<td colspan="4"><center><b>Maio</b></center></td>
<td colspan="5"><center><b>Junho</b></center></td>
<td colspan="4"><center><b>Julho</b></center></td>
<td colspan="5"><center><b>Agosto</b></center></td>
<td  colspan="4" rowspan="2" ><center><b> Responsável</b></center> </td>
<td rowspan="2"> <center><b>Concluído</b></center> </td>

  </tr>

<tr>
 <td colspan="3" >Nº</td>
 <td colspan="3">Atividade</td>

 <td >06/abr</td>
 <td >13/abr</td>
 <td >20/abr</td>
 <td >27/abr</td>

<td >04/maio</td>
 <td >11/maio</td>
 <td >18/maio</td>
 <td >25/maio</td>

<td >01/jun</td>
 <td >08/jun</td>
 <td >15/jun</td>
 <td >22/jun</td>
 <td >29/jun</td>

<td >06/jul</td>
 <td >13/jul</td>
 <td >20/jul</td>
 <td >27/jul</td>

<td >03/ago</td>
 <td >10/ago</td>
 <td >17/ago</td>
 <td >24/ago</td>
 <td >31/ago</td>


 </tr>
<tr>
 <td colspan="3">1</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">2</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">3</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">4</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">5</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">6</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">7</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">8</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">9</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">10</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">11</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">12</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">13</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">14</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
<tr>
 <td colspan="3">15</td>
<td colspan="3"></td>
 <td colspan="4"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
 <td colspan="5"></td>
<td colspan="4"></td>
<td ></td>
</tr>
</table>


@viniciussoaresti @MatheusDias18  Segue cronograma semanal.

**Comment by BarrosPedro** [comment]
Segue acima Cronograma Semanal.

**Comment by vinisoaresti** [comment]
@BarrosPedro Após analisar a PR já 'mergeada', atualize o documento e feche essa issue.

**Comment by BarrosPedro** [comment]
Cronograma finalizado.
