### ISSUE TITLE
Assinar Termos de Compromisso

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#21]
Localizados em /docs, realizar também a limpeza do repositórioo (retirar os mesmos após impressão, e demais arquivos desnecessários).

**Comment by fabriciofx** [comment]
@viniciussoaresti @MatheusDias18 @BarrosPedro Estes arquivos ainda estão sendo editados e analisados. Quando estiverem prontos, seu orientador vai apresentá-los a vocês, ok?

**Comment by vinisoaresti** [comment]
@fabriciofx Okay, obrigado. Portanto, fecharei a issue.
