### ISSUE TITLE
Semana 1: Atividades Requeridas Antes da Primeira Sprint

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#26]
- [x] Ambiente pronto (em parte sim, falta teste);
- [x] Escopo do Projeto (prioridades pelo cliente);
- [x] Cronograma de Tarefas; 
- [x] Cronograma de Atividades;
- [ ] Commit no git com a estrutura de pastas do projeto (etc,doc,hiber,java(util,modelo,dao,bean,servlets)) - @viniciussoaresti;

**Comment by vinisoaresti** [comment]
@MatheusDias18 Lembre de dar upload nos documentos e fechar a issue #13.

**Comment by MatheusDias18** [comment]
@viniciussoaresti Issue fechada.

**Comment by vinisoaresti** [comment]
Movido para issue #31
