### ISSUE TITLE
Documento de requisitos

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#3]
1a fase:
Com diagramas
Descrever cliente
Usuários do sistema
Definir o sistema (escopo: o que é, o que serve e o que vai ter)
Requisitos (funcionais e não funcionais(pode colocar as tecnologias aqui)) -- Priorizar
Tecnologias utilizadas (linguagem, bibliotecas, plugins, descrição detalhada (pq de usar, benefícios))

IDEIA: backup na nuvem e hd externo

**Comment by viniciussoaresti** [comment]
Seguir diagrama de casos de uso em um dos seguintes esquemas anexados.
![Diagramas](https://user-images.githubusercontent.com/36902457/37875360-57a977f4-3014-11e8-830a-b1b906c01275.jpeg)

**Comment by viniciussoaresti** [comment]
Consertar algumas funções como "inativar", onde não fazem sentido e pensar melhor no sistema como um todo.

**Comment by vinisoaresti** [comment]
Justificar o texto.

**Comment by vinisoaresti** [comment]
Pesquisar criptografia de senha.

**Comment by vinisoaresti** [comment]
Dado upload, faltando:
-Diagramas de uso e de classe
-Entradas e saídas das funcionalidades

**Comment by MatheusDias18** [comment]
O requisito de emissão de nota fiscal eletrônica (RF007), pode ser considerado um requisito não funcional, **Analisar isto**

**Comment by vinisoaresti** [comment]
Finalizada, faltando apenas algumas alterações mínimas.
