### ISSUE TITLE
Diagramas de Caso de Uso

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#4]
Classe, uso, 1 ou 2 de sequência (funcionalidades principais).

**Comment by vinisoaresti** [comment]
O diagrama de uso deve ser concentrado em apenas um, seguindo um dos dois modelos anexados:
![whatsapp image 2018-03-25 at 9 18 51 am](https://user-images.githubusercontent.com/36902457/37875460-00f6eb4c-3016-11e8-9730-aaddbed0479d.jpeg)

**Comment by vinisoaresti** [comment]
Algumas funções incluem o "consultar", entre outras, então deve-se fazer explícita essa ligação. Exemplo: Deletar produto do estoque permanentemente -> consultar produto -> deletar produto

**Comment by fabriciofx** [comment]
@viniciussoaresti Procure ser mais específico no título das issues. "Diagramas" é muito genérico. Diagrama de quê? Lembre-se que os títulos serão usados para futuras buscas.

**Comment by vinisoaresti** [comment]
@fabriciofx Obrigado pela sugestão, alterando agora.

**Comment by MatheusDias18** [comment]
Ocorreu uma alteração no diagrama de casos de uso na sessão de estoque, que deverá também ser feita na issue #3  .

**Comment by vinisoaresti** [comment]
@MatheusDias18 Que alteração? **SEJA ESPECÍFICO.**

**Comment by MatheusDias18** [comment]
A sessão de estoque do diagrama de casos de uso, não tem mais cadastrar nem inativar, por falta de lógica para o sistema.

**Comment by vinisoaresti** [comment]
@MatheusDias18 Agora sim.

**Comment by MatheusDias18** [comment]
Prévia do diagramas de casos de uso **em anexo** 
![usecase diagram0](https://user-images.githubusercontent.com/36974652/37999941-99a0e6a4-31fb-11e8-81b8-7d75ffa8b7f4.jpg)

**Comment by MatheusDias18** [comment]
Diagramas de casos de uso concluído, favor avisem-me se necessitar de alterações!

**Comment by MatheusDias18** [comment]
Finalizada até segunda ordem.
