### ISSUE TITLE
Adequar o projeto às especificações modelo

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#6]
Segue modelo de repósitorio de PPO: https://github.com/ifpe-cti/modelo-projeto-ppo

**Comment by MatheusDias18** [comment]
Issue concluida.

**Comment by fabriciofx** [comment]
@MatheusDias18 @viniciussoaresti Olha, em qual PR foi feita a atualização do `README.md`? Não localizei esse PR. Como é que o arquiteto pode fazer o review das mudanças? Eu mesmo vi vários defeitos e não pude comentá-los porque não teve PR. **Tem** que fazer as mudanças via PR.

**Comment by vinisoaresti** [comment]
@fabriciofx mandei a dúvida exatamente sobre isso via email, um tempo atrás.

**Comment by vinisoaresti** [comment]
@fabriciofx As permissões já foram definidas pra a pull request ser feita em todos os casos, foi mal. Se o sr. puder abrir uma issue pra atualizar o 'README.md' e descrever quais as mudnças necessárias, seria grato. Ou nessa própria issue mesmo.

**Comment by fabriciofx** [comment]
@viniciussoaresti Se você acha interessante atualizar o `README.md`, poderia abrir uma issue ou escrever algum comentário lá em [modelo-projeto-ppo](https://github.com/ifpe-cti/modelo-projeto-ppo)? Agradeço antecipadamente.

**Comment by vinisoaresti** [comment]
@fabriciofx Me referi aos defeitos citados em um de seus comentários, em relação ao `README.md`, para que disesse quais foram os erros e que corrigíssemos aqui.
