### ISSUE TITLE
Cronograma de Atividades e Backlog do Produto

### ISSUE THREAD

**Issue by vinisoaresti** [ifpe-cti/sysgraph#8]
Quebrar os requisitos funcionais em atividades;
Backlog produto;
Cronograma (contar quantas semans há até agosto, ser realistae tomar cuidado com os feriados) e divisão de quem realizará as atividades;

**Comment by fabriciofx** [comment]
@viniciussoaresti Novamente, olhe o título da issue. ETAPA 2 o quê? Onde está a ETAPA 1?

**Comment by vinisoaresti** [comment]
@fabriciofx Mais uma vez, obrigado, corrigindo agora.

**Comment by vinisoaresti** [comment]
Reunião será realizada hoje via skype, com transcrição colocada aqui.

**Comment by fabriciofx** [comment]
@viniciussoaresti Quem é o orientador do seu grupo? Favor resolver a issue #9 o mais depressa possível.

**Comment by vinisoaresti** [comment]
@fabriciofx colocarei lá.

**Comment by BarrosPedro** [comment]
@viniciussoaresti @MatheusDias18  Segue link de exemplo do cronograma semanal do projeto, http://www.eterfs.com.br/material/mecanica/cronograma.xls

**Comment by fabriciofx** [comment]
@BarrosPedro Arquivos binários são difíceis de versionar, fora que este precisa de um programa específico para visualizar. Recomendo você criar um arquivo no formato Markdown com o conteúdo desse arquivo.

**Comment by vinisoaresti** [comment]
@BarrosPedro https://github.com/jonmagic/copy-excel-paste-markdown pode ajudar.

**Comment by BarrosPedro** [comment]
@fabriciofx Ok, será feito.

**Comment by BarrosPedro** [comment]
@viniciussoaresti Valeu

**Comment by BarrosPedro** [comment]
@MatheusDias18 @viniciussoaresti  Segue versão final do cronograma semanal. 

[Cronograma Semanal PPO.xlsx](https://github.com/ifpe-cti/grafica/files/1854141/Cronograma.Semanal.PPO.xlsx)

**Comment by MatheusDias18** [comment]
ok, ótimo trabalho!

**Comment by fabriciofx** [comment]
@MatheusDias18 @BarrosPedro Nope. Precisa ainda converter para o formato Markdown.

**Comment by vinisoaresti** [comment]
@fabriciofx segundo @BarrosPedro , a ferramenta de conversão que achamos não funciona para células mescladas, dando um trabalho imenso.

**Comment by BarrosPedro** [comment]
@fabriciofx Certo, farei novamente,

**Comment by BarrosPedro** [comment]
@viniciussoaresti Pode deixar, eu faço.

**Comment by fabriciofx** [comment]
@viniciussoaresti Precisa **mesmo** de células mescladas? Em todo o caso, na pior das hipóteses, vocês podem fazer o documento em Markdown e apenas a tabela em HTML, usando as tags `<table>...</tables>`. O formato Markdown/GH permite esse tipo de coisa. No entanto, não convém abusar, senão o formato Markdown perde o sentido.

Favor escrever [nessa](https://github.com/ifpe-cti/modelo-projeto-ppo/issues/3) issue esse problema para ser coberto no tutorial.

**Observação:** viu como é importante que **tudo** vire uma issue? Essa conversa implica em um comentário ou outra issue, até em outro projeto.

**Comment by BarrosPedro** [comment]
Issue #8 Finalizada.

**Comment by BarrosPedro** [comment]
@viniciussoaresti Só consigo fechar as issues que eu abro. A issue #8 já pode ser fechada.
