### ISSUE TITLE
Atualizar o README do projeto

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/sysgraph#9]
@viniciussoaresti, @MatheusDias18, @BarrosPedro vocês colocaram o `README.md` errado. O que deveria ter sido usado como base é este [aqui](https://github.com/ifpe-cti/modelo-projeto-ppo/blob/master/README.md). Favor atualizar.

**Comment by vinisoaresti** [comment]
@fabriciofx Sim senhor.

**Comment by vinisoaresti** [comment]
Fechando issue, duplicada, já está prevista mudança na issue #6 .
